import Navbar from "../Components/Navbar";
import Footer from "../Components/Footer";
import { FaLaptop, FaTwitter } from "react-icons/fa";
import { getAllTopics } from "../Lib/Data";

/**
 * @description Retrieves an array of topics using the `getAllTopics()` utility and
 * prepares it to be statically generated by exporting it as a React component's props.
 * 
 * @returns {object} An instance of an object with one property named "props" whose
 * value is another object containing a single property named "topics" with a value
 * of allTopics.
 */
export const getStaticProps = () => {
  const allTopics = getAllTopics();
  return {
    props: {
      topics: allTopics,
    },
  };
};

/**
 * @description Renders an "About" page, displaying a logo, a brief introduction, and
 * two buttons to view Soumyajit's works on his website and follow him on Twitter.
 * It accepts a `topics` object as a prop and uses it to populate the Navbar component.
 * 
 * @param {object} obj - Named `topics`. It accepts an object with key-value pairs,
 * where keys represent topics and values are unknown or omitted. The purpose of this
 * parameter is to pass topics data from outside the component.
 * 
 * @param {object} obj.topics - Used to pass topics data to the `Navbar` component.
 * 
 * @returns {JSX.Element} A React component that renders an HTML structure consisting
 * of several elements including a navbar, images, text, buttons, and footer.
 */
function about({ topics }) {
  return (
    <div className="min-h-screen relative bg-white dark:bg-gray-900">
      <Navbar topics={topics} />
      <div className="max-w-2xl pt-20 pb-32 px-6 text-center mx-auto">
        <div className="h-64 w-full justify-center flex">
          <img src="/about.png" className="h-64" />
        </div>
        <h2 className="text-3xl font-semibold text-gray-700 py-4 dark:text-gray-200">
          Hi,{" "}
          <span className="bg-indigo-400 text-white rounded px-1 dark:bg-indigo-500">
            I’m Soumyajit
          </span>{" "}
          . Nice to meet you.
        </h2>
        <p className="text-gray-600 mt-4 dark:text-indigo-200">
          I am a self taught developer currently pursuing IMSC in Maths and
          Computing in BIT Mesra. My field of Interest's are building new Web
          Technologies and Products and also in areas related to Deep Learning
          and Natural Launguage Processing.
        </p>

        <div className="text-center pt-8">
          <button className="bg-indigo-500 px-3 py-1 font-semibold text-white inline-flex items-center space-x-2 rounded dark:bg-indigo-600">
            <FaLaptop />
            <a
              rel="noopener noreferrer"
              target="_blank"
              href="https://soumyajit.vercel.app/"
            >
              See My Works
            </a>
          </button>

          <button className="bg-indigo-500 px-3 py-1 font-semibold text-white inline-flex items-center space-x-2 rounded ml-3 dark:bg-indigo-600">
            <FaTwitter />
            <a
              className="twitter-follow-button"
              rel="noopener noreferrer"
              target="_blank"
              href="https://twitter.com/austinL394"
            >
              Follow Me
            </a>
          </button>
        </div>
      </div>
      <Footer />
    </div>
  );
}

export default about;
